added nodegroup_type to nodegroup model
selectel/terraform-provider-selectel pull request #203
Opened 2022-07-12 13:21 UTC by TawR1024

This PR will resole  #202

Changes:

- According to new MKS API specification added` nodegroup_type` field to `nodegroup` schema.
- mks-go version upgraded to v0.11.0

2022-07-13 15:17 UTC, kolsean commented on selectel/resource_selectel_mks_nodegroup_v1.go
> +			},
It seems that `nodegroup_type` should have `ForceNew: true` property.
Also It would be great if we add validation func for this values.

2022-07-13 15:19 UTC, kolsean requested changes
Looks good but need to make some changes.
Also please update the doc examples.

2022-07-14 09:47 UTC, dkder3k approved these changes
Looks good. Thank you!

2022-07-14 19:11 UTC, kolsean commented on selectel/resource_selectel_mks_nodegroup_v1_test.go
> +  nodegroup_type = STANDARD
If we declare this field as computed in the resource schema it should not be in manifest.
Also it breaks acceptance tests.
Please remove this line.

2022-07-14 19:13 UTC, kolsean commented on selectel/resource_selectel_mks_nodegroup_v1_test.go
> +					resource.TestCheckResourceAttr("selectel_mks_nodegroup_v1.nodegroup_tf_acc_test_1", "nodegroup_type", "STANDARD"),
we also can add the same check to update test case

2022-07-15 15:22 UTC, kolsean approved these changes
LGTM!

2022-07-15 15:23 UTC, merged