Add handling for private kube API clusters
selectel/terraform-provider-selectel pull request #204
Opened 2022-07-19 07:18 UTC by dkder3k

2022-07-19 14:28 UTC, kolsean requested changes

2022-07-19 14:28 UTC, kolsean commented on website/docs/r/mks_cluster_v1.html.markdown
> +
Let's also mention that "changing this creates a new cluster".

2022-08-04 08:34 UTC, TawR1024 approved these changes
Nice! Thank you for your work.

2022-08-09 20:15 UTC, kolsean approved these changes

2022-08-09 20:16 UTC, merged