Add backup retention days parameter to datastore
selectel/terraform-provider-selectel pull request #231
Opened 2023-06-28 14:55 UTC by Rey-Lane

To retain datastore backups more than seven days, we have to add new parameter that contains the number of backups retentions days

2023-07-10 07:13 UTC, Gogen120 approved these changes

2023-07-18 08:46 UTC, TawR1024 requested changes

2023-07-18 08:46 UTC, TawR1024 commented on selectel/resource_selectel_dbaas_datastore_v1.go
> +	BackupRetentionDays, DaysIsOk := d.GetOk("backup_retention_days")
Is it necessary to make `BackupRetentionDays` as package variable ? I suppose it should be defined in local scope.
Also, `ok` value should be named as `ok`, so please rename `DaysIsOk` to ok.

2023-07-18 08:46 UTC, TawR1024 commented on selectel/resource_selectel_dbaas_mysql_datastore_v1.go
> +	BackupRetentionDays, DaysIsOk := d.GetOk("backup_retention_days")
same,  please rename variables.

2023-07-27 17:34 UTC, TawR1024 approved these changes

2023-07-31 20:36 UTC, kolsean approved these changes

2023-07-31 20:37 UTC, merged