Fix dbaas_postgresql_extension resource doc
selectel/terraform-provider-selectel pull request #241
Opened 2023-10-16 09:56 UTC by Gogen120

It used to have copy pasted documentation from deprecated dbaas_extension resource. So it didn't get the updated documentation

2023-10-24 09:53 UTC, Vasilek15 requested changes

2023-10-24 09:53 UTC, Vasilek15 commented on website/docs/r/dbaas_postgresql_extension_v1.html.markdown
> +  Creates and manages a PostgreSQL extension in Selectel Managed Databases Service using public API v1.
```suggestion
  Creates and manages a PostgreSQL extension in Selectel Managed Databases using public API v1.
```

2023-10-24 09:53 UTC, Vasilek15 commented on website/docs/r/dbaas_postgresql_extension_v1.html.markdown
> +
For more information about extensions, see the official Selectel documentation for [PostgreSQL](https://docs.selectel.ru/cloud/managed-databases/postgresql/add-extensions/), [PostgreSQL for 1C](https://docs.selectel.ru/cloud/managed-databases/postgresql-for-1c/extensions-1c/), and [PostgreSQL TimescaleDB](https://docs.selectel.ru/cloud/managed-databases/timescaledb/add-extensions/).

2023-10-24 09:53 UTC, Vasilek15 commented on website/docs/r/dbaas_postgresql_extension_v1.html.markdown
> +* `available_extension_id` - (Required) Unique identifier of the available extension that you want to create. Changing this creates a new extension. Not applicable to a Redis datastore. Retrieved fro
```suggestion
* `available_extension_id` - (Required) Unique identifier of the available extension that you want to create. Changing this creates a new extension. Retrieved from the [selectel_dbaas_available_extension_v1](https://registry.terraform.io/providers/selectel/selectel/latest/docs/data-sources/dbaas_available_extension_v1) data source.
```

2023-10-24 09:53 UTC, Vasilek15 commented on website/docs/r/dbaas_postgresql_extension_v1.html.markdown
> +* `database_id` - (Required) Unique identifier of the associated database. Changing this creates a new extension. Not applicable to a Redis datastore. Retrieved from the [selectel_dbaas_postgresql_da
```suggestion
* `database_id` - (Required) Unique identifier of the associated database. Changing this creates a new extension. Retrieved from the [selectel_dbaas_postgresql_database_v1](https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/dbaas_postgresql_database_v1) resource.
```

2024-02-28 07:05 UTC, TruePack approved these changes

2024-02-28 07:15 UTC, TruePack approved these changes

2024-02-28 07:15 UTC, merged