Add kafka support
selectel/terraform-provider-selectel pull request #248
Opened 2024-01-16 12:12 UTC by Gogen120

- Add a new resource selectel_dbaas_kafka_acl_v1 to manage Kafka's ACLs
- Add a new resource selectel_dbaas_kafka_topic_v1 to manage Kafka's Topics
- Add a new resource selectel_dbaas_kafka_datastore_v1 to manage Kafka datastores
- Update dbaas-go version to v0.10.0

2024-01-25 10:25 UTC, TruePack commented on selectel/resource_selectel_dbaas_kafka_datastore_v1.go
> +	if flavorIDOk == flavorOk {
Здесь скрыта неявная логика, что проверяется только отсутствие двух параметров одновременно, а одновременное присутствие проверяется валидацией терраформа.
Я бы здесь явно указал 
if !flavorIDOk && !flavorOk

2024-01-25 10:25 UTC, TruePack commented on selectel/resource_selectel_dbaas_kafka_datastore_v1.go
> +		datastoreCreateOpts.Flavor = flavor
А для чего иметь две опции проброса флейвора? Ведь по сути у нас здесь уже есть flavor.id, который можно передать в datastoreCreateOpts.FlavorID

2024-01-25 10:43 UTC, Gogen120 commented on selectel/dbaas.go
> +func dbaasACLV1StateRefreshFunc(ctx context.Context, client *dbaas.API, aclID string) resource.StateRefreshFunc {
Да, думаю стоит перенести. Но уже отдельным мр-ом, так как к кафке это не особо имеет отношение

2024-01-25 10:45 UTC, Gogen120 commented on selectel/dbaas.go
> +		MinTimeout: 3 * time.Second,
Это перекочевало из других ресурсов, так как там такие же поля используются. Мб, стоит это пересмотреть

2024-01-25 10:57 UTC, Gogen120 commented on selectel/resource_selectel_dbaas_kafka_datastore_v1.go
> +		datastoreCreateOpts.Flavor = flavor
Не очень понял вопроса. Но тут есть возможность указывать фиксированные или гибкие флаворы. Соответственно, при указании гибкого мы не знаем flavorID и он будет null

2024-01-25 10:57 UTC, Gogen120 commented on selectel/resource_selectel_dbaas_kafka_acl_v1.go
> +				ForceNew: false,
Судя по доке, оно по дефолту `true`, но мб не туда посмотрел

2024-01-25 10:58 UTC, Gogen120 commented on selectel/resource_selectel_dbaas_kafka_acl_v1.go
> +	selMutexKV.Lock(datastoreID)
Для лока связанных ресурсов. Мб, это что-то устаревшее, надо проверить

2024-01-25 10:59 UTC, Gogen120 commented on selectel/resource_selectel_dbaas_kafka_datastore_v1.go
> +	if flavorIDOk == flavorOk {
Done

2024-01-25 11:22 UTC, TruePack commented on selectel/dbaas.go
> +		MinTimeout: 3 * time.Second,
Самый оптимальный вариант тут -- живые тесты на проде, прям покурлить, посмотреть время примерное.
И по этим данным выставить числа. А то сейчас пальцем в небо. Предлагаю все-таки пересмотреть подход к параметризации.

2024-01-25 11:24 UTC, TruePack commented on selectel/resource_selectel_dbaas_kafka_datastore_v1.go
> +		datastoreCreateOpts.Flavor = flavor
Не подумал про гибкие флейворы

2024-01-25 11:27 UTC, TruePack commented on selectel/resource_selectel_dbaas_kafka_acl_v1.go
> +				ForceNew: false,
Я в доке ничего не нашел, руководствуюсь дефолтным поведением гошки

2024-01-25 12:06 UTC, Gogen120 commented on selectel/resource_selectel_dbaas_kafka_acl_v1.go
> +				ForceNew: false,
Проверил, действительно, можно не указывать при `false`

2024-01-25 16:20 UTC, Vasilek15 requested changes

2024-01-26 06:25 UTC, Gogen120 commented on selectel/dbaas.go
> +		MinTimeout: 3 * time.Second,
Потюнил значения для ресурсов кафки. Остальные уже поправлю в отдельном мр-е

2024-02-06 07:47 UTC, TruePack commented
lgtm

2024-02-06 07:47 UTC, TruePack approved these changes

2024-02-06 07:48 UTC, merged