Added entities for work with DNS v2 API.
selectel/terraform-provider-selectel pull request #249
Opened 2024-01-23 19:17 UTC by dchudik

Планируется публичный релиз DNS v2 API.
В данный момент API v2 доступно для использования, но докуметации и UI апдейта ещё нет.

Добавил новые ресурсы:
* `selectel_domains_zone_v2`
* `selectel_domains_rrset_v2`

Добавил новые datasource:
* `selectel_domains_zone_v2`
* `selectel_domains_rrset_v2`

Обновил версию библиотеки domains-go.

2024-01-24 19:31 UTC, dchudik commented
В данный момент немножко хромает прод, могут быть проблемы при прогоне - уже фиксим. 
Как буду уверен, что всё окей - оставлю сообщение ниже.

2024-01-26 12:21 UTC, dchudik commented
Исправили то что хотели.
Готов к проверке.

2024-01-30 06:19 UTC, Gogen120 commented on selectel/resource_selectel_domains_rrset_v2.go
> +func setRrsetToResourceData(d *schema.ResourceData, rrset *domainsV2.RRSet) error {
А не стоит этот метод перетащить в `domains_v2.go`? Так как он для дата сорсов и для ресурсов используется. Кажется, что это что-то общее

2024-01-30 06:19 UTC, Gogen120 commented on selectel/resource_selectel_domains_rrset_v2.go
> +				Required: true,
Я немного запутался, но не нужно ли выставлять поле `ForceNew: true` для неизменяемых полей?

2024-01-30 06:19 UTC, Gogen120 commented on selectel/resource_selectel_domains_zone_v2.go
> +func setZoneToResourceData(d *schema.ResourceData, zone *domainsV2.Zone) error {
Тоже кажется, что можно перенести в `domains_v2.go` как общую штуку для всех ресурсов, связанных с зонами

2024-01-30 06:20 UTC, Gogen120 commented
Еще, как я помню, надо бы документацию добавить в `website/docs` с описанием ресурсов

2024-02-01 13:50 UTC, dchudik commented on selectel/resource_selectel_domains_zone_v2.go
> +func setZoneToResourceData(d *schema.ResourceData, zone *domainsV2.Zone) error {
Исправил

2024-02-01 13:51 UTC, dchudik commented on selectel/resource_selectel_domains_rrset_v2.go
> +				Required: true,
Добавил `ForceNew: true` для неизменяемых полей в ресурсах zone_v2 и rrset_v2

2024-02-01 13:51 UTC, dchudik commented on selectel/resource_selectel_domains_rrset_v2.go
> +func setRrsetToResourceData(d *schema.ResourceData, rrset *domainsV2.RRSet) error {
Исправил

2024-02-01 13:52 UTC, dchudik commented
Добавил документацию по образцу остальных команд.
Исправил замечания с ревью:
1. Добавил ForceNew для неизменяемых полей
2. Перенес общие методы в domains_v2

2024-02-02 04:27 UTC, Gogen120 approved these changes

2024-02-06 09:33 UTC, sel-bukharov requested changes

2024-02-06 09:33 UTC, sel-bukharov commented on selectel/domains_v2.go
> +		}
Here we can invert the condition to reduce nesting:

```
	record, isOk := recordItem.(map[string]interface{})
	if !isOk {
		continue
	}
	records = append(records, domainsV2.RecordItem{
		Content:  record["content"].(string),
		Disabled: record["disabled"].(bool),
	})
```

2024-02-06 09:33 UTC, sel-bukharov commented on selectel/data_source_selectel_domains_rrset_v2.go
> +	ErrFoundMultipleRRsets = errors.New("found multiple rrsets")
Variables and methods have different naming styles, and I found three kinds below, such as `Rrset`, `rrset` and `RRset`. I suggest renaming them to be named like `RRSet`.

2024-02-06 10:53 UTC, sel-bukharov commented on selectel/domains_v2.go
> +		}
After discussion with @TruePack, we have concluded that the code above is the golang way. Feel free resolve my comment.

2024-02-06 11:52 UTC, TruePack requested changes

2024-02-06 11:52 UTC, TruePack commented on selectel/domains_v2.go
> +	projectID := config.ProjectID
Пожалуйста, давай не завязываться на этот project_id, а сделаем его обязательным в датасорсе и всегда брать из него.

2024-02-06 11:52 UTC, TruePack commented on selectel/domains_v2.go
> +	projectID := config.ProjectID
Это поле используется сейчас только для импорта ресурсов dbaas/mks из-за особенности работы с API.

2024-02-06 11:52 UTC, TruePack commented on selectel/domains_v2.go
> +	defaultAPIURL := "https://api.selectel.ru/domains/v2"
Предалагаю не хардкодить здесь адреса, а перейти на service-discovery от keystone.

2024-02-06 11:52 UTC, TruePack commented on selectel/resource_selectel_domains_rrset_v2.go
> +	selMutexKV.Lock(zoneID)
Для чего локи используются?

2024-02-06 12:59 UTC, dchudik commented on selectel/domains_v2.go
> +	projectID := config.ProjectID
Правильно ли я понял, что если у нас зоны и ррсеты привязаны к селектеловскому проекту, то тогда сделать project_id обязательным в датасорсах И В РЕСУРСАХ?

2024-02-06 19:04 UTC, dchudik commented on selectel/resource_selectel_domains_rrset_v2.go
> +	selMutexKV.Lock(zoneID)
Делал по образцу первой версии, понял что сейчас можно обойтись без них

2024-02-06 19:06 UTC, dchudik commented on selectel/domains_v2.go
> +	defaultAPIURL := "https://api.selectel.ru/domains/v2"
Раньше урл был захардкожен в либе. 
Сейчас мы его вынесли, но эндпоинта для DNS в каталоге Keystone - нет.
Поэтому захардкодили.

2024-02-06 19:06 UTC, dchudik commented on selectel/domains_v2.go
> +		}
Решил исправить на твой вариант.

2024-02-06 19:08 UTC, dchudik commented on selectel/domains_v2.go
> +	projectID := config.ProjectID
Сделал project_id обязательным для всех сущностей, которые добавил.
Понял, что это поможет пользователю более четко контролировать в каких проектах создаются ресурсы.

2024-02-06 19:14 UTC, dchudik commented on selectel/data_source_selectel_domains_rrset_v2.go
> +	ErrFoundMultipleRRsets = errors.New("found multiple rrsets")
Исправил названия. Оставил только два стиля: RRSet и rrset

2024-02-06 20:37 UTC, dchudik commented
Убрал замечание из линтера.
Оставил два варианта наименования RRSet и rrset.
Сделал поле project_id обязательным в сущностях, которые добавил.

Остался вопрос с тестами для импорта.
Мы используем проектный токен Keystone. И поэтому при импорте ресурсов важно чтобы параметр project_id в конфиге был установлен. 
Если делать по образцу остальных команд, то тесты проходить не будут. При этом тест для импорта у CRaaS (TestAccCRaaSRegistryV1ImportBasic) тоже не работает. Остальные тесты проверить не удалось.
Проблема кроется в том, что функция testAccCheckSelectelImportEnv устанавливает значение переменной SEL_PROJECT_ID, но дальше при импорте не обновляется config. И когда мы в функции импорта берем config.ProjectID - мы берем старое значение (с прошлого запуска тестов).
Нашел два варианта решения проблемы:
1. В функции импорта использовать os.Getenv("SEL_PROJECT_ID"). 
2. При запуске тестов на импорт установить переменную окружения SEL_PROJECT_ID. В рамках будет создана зона и эта же зона будет импортирована.

Остановился на втором варианте.

2024-02-12 17:41 UTC, TruePack commented on selectel/resource_selectel_domains_zone_v2.go
> +	zone, err := getZoneByName(ctx, client, zoneName)
Чуток поломался. Берется ID, а называется Name.

2024-02-12 17:41 UTC, TruePack commented on selectel/resource_selectel_domains_zone_v2.go
> +	zone, err := getZoneByName(ctx, client, zoneName)
Есть ли смысл от таких алиасов?

2024-02-12 18:01 UTC, dchudik commented on selectel/resource_selectel_domains_zone_v2.go
> +	zone, err := getZoneByName(ctx, client, zoneName)
При импорте ресурса `domains_zone_v2` решил, что клиенту проще импортнуть зону по имени, так как она уникальна.
А поскольку при импорте имя будет вместо id ресурса, то и использую конструкцию `d.Id()`
Команда для импорта будет выглядеть следующим образом:
```
$terraform import domains_zone_v2.domain1_ru domain.ru.
```
Тогда не придется лезть в панеле на каждый смотреть айдишник.

Что-то похожее реализовал и в rrset.

2024-02-13 11:46 UTC, dchudik commented
Добавил комментарии в функции импорта в ресурсах `domains_v2`, для большей ясности кода.
Убрал объявление переменных: zoneID := d.Id() и rrsetID := d.Id(). Использую сразу d.Id().

2024-02-20 11:42 UTC, borisenko-o requested changes

2024-02-20 11:42 UTC, borisenko-o commented on website/docs/d/domains_rrset_v2.html.markdown
> +* `ttl` - RRSet TTL.
RRSet time-to-live in seconds.

2024-02-21 21:03 UTC, dchudik commented on website/docs/d/domains_domain_v1.html.markdown
> +~> **Note:** This is legacy datasource. Using the `selectel_domains_zone_v2` datasource. They utilize different API and created zones live on different authoritative servers. Zone created in v2 API i
Заменил Note на Warning. Чтобы выглядело как [тут](https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/dbaas_database_v1)

2024-02-21 23:11 UTC, dchudik reviewed
Исправил замечания.

2024-02-22 10:41 UTC, borisenko-o requested changes

2024-02-22 10:41 UTC, borisenko-o commented on website/docs/d/domains_rrset_v2.html.markdown
> +* `zone_id` - (Required) (Required) Unique identifier of the zone. Retrieved from the [selectel_domains_zone_v2](https://registry.terraform.io/providers/selectel/selectel/latest/docs/resources/domain
после тире задублировалось: (Required) (Required)

2024-02-22 10:41 UTC, borisenko-o commented on website/docs/r/domains_rrset_v2.html.markdown
> +## Example usage
Посмотрела, ок

2024-02-22 12:02 UTC, dchudik reviewed
Исправил замечания

2024-02-22 13:09 UTC, borisenko-o requested changes

2024-02-22 13:39 UTC, dchudik commented on website/docs/d/domains_zone_v2.html.markdown
> +* `delegation_checked_at` - Time when DNS Hosting checked if the zone was delegated to Selectel NS servers in RFC 3339 timestamp format.
Добавил

2024-02-22 13:39 UTC, dchudik commented on website/docs/r/domains_zone_v2.html.markdown
> +* `delegation_checked_at` - Time when DNS Hosting checked if the zone was delegated to Selectel NS servers in RFC 3339 timestamp format.
Добавил

2024-02-22 18:57 UTC, TruePack approved these changes

2024-02-26 08:33 UTC, dchudik commented
Удалил datasource для domains_v2 так как они противоречат концепции datasources в terraform.
Результаты запуска тестов:
```
=== RUN   TestAccDomainsRRSetV2Basic
--- PASS: TestAccDomainsRRSetV2Basic (72.31s)

=== RUN   TestAccDomainsZoneV2Basic
--- PASS: TestAccDomainsZoneV2Basic (58.27s)

=== RUN   TestAccDomainsZoneV2ImportBasic
--- PASS: TestAccDomainsZoneV2ImportBasic (6.15s)

=== RUN   TestAccDomainsRRSetV2ImportBasic
--- PASS: TestAccDomainsRRSetV2ImportBasic (12.95s)
```

2024-02-26 10:13 UTC, merged