Fix extensions for kafka resource docs
selectel/terraform-provider-selectel pull request #250
Opened 2024-02-06 12:22 UTC by Gogen120

2024-02-08 11:12 UTC, Vasilek15 requested changes

2024-02-08 11:20 UTC, Gogen120 commented on website/docs/d/dbaas_configuration_parameter_v1.html.markdown
> +Provides a list of configuration parameters available for Managed Databases. For more information about configuration parameters, see the official Selectel documentation for [PostgreSQL](https://docs
Fixed

2024-02-08 11:20 UTC, Gogen120 commented on website/docs/d/dbaas_datastore_type_v1.html.markdown
> +data "selectel_dbaas_datastore_type_v1" "dt" {
Fixed

2024-02-08 11:20 UTC, Gogen120 commented on website/docs/d/dbaas_prometheus_metric_token_v1.html.markdown
> +Provides a list of tokens for Prometheus available in Managed Databases. For more information about tokens for Prometheus, see the official Selectel documentation for [PostgreSQL](https://docs.select
Fixed

2024-02-12 17:56 UTC, TruePack approved these changes

2024-02-12 17:57 UTC, merged