Add 'floating_ips' field to datastore creation
selectel/terraform-provider-selectel pull request #253
Opened 2024-02-16 09:26 UTC by Rey-Lane

2024-03-05 11:35 UTC, TruePack requested changes

2024-03-05 11:35 UTC, TruePack commented on selectel/resource_selectel_dbaas_datastore_v1.go
> +				Optional: true,
А еще это поле никак не имплементируется в Update, при этом у него forceNew: false

2024-04-12 08:31 UTC, TruePack commented on selectel/dbaas.go
> +func refreshOutputsDiff(_ context.Context, diff *schema.ResourceDiff, _ interface{}) error {
Слишком общее название функции в таком широком пакете, предлагаю как-то конкретиризировать.

2024-04-12 09:26 UTC, Rey-Lane commented on selectel/dbaas.go
> +		}
Потому что мы не хотим прикреплять плавающий адрес ко всем свободным репликам, мы хотим прикрепить столько адресов, сколько содержится в переменной replicasDiff

2024-04-12 11:29 UTC, sel-bukharov commented on selectel/dbaas.go
> +		}
Понял. Этот тред тогда можно закрывать

2024-04-17 09:42 UTC, TruePack approved these changes

2024-04-17 10:22 UTC, merged