fix: fix bug with flavors
selectel/terraform-provider-selectel pull request #274
Opened 2024-04-22 10:41 UTC by TawR1024

For https://github.com/selectel/terraform-provider-selectel/issues/273

* fixed resource_selectel_mks_nodegroup_v1
* added some new test cases for resource_selectel_mks_nodegroup_v1
* updated docs

2024-04-22 11:04 UTC, pavelpereyma approved these changes

2024-04-22 13:30 UTC, yaroslaver approved these changes
LGTM

2024-04-22 15:20 UTC, kolsean requested changes

2024-04-23 05:29 UTC, TawR1024 commented on selectel/resource_selectel_mks_nodegroup_v1.go
> +				ForceNew: false,
My bad, that was unexpected and not necessary change.
Fixed it.

2024-04-23 09:57 UTC, merged