update CHANGELOG.md
selectel/terraform-provider-selectel pull request #308
Opened 2024-11-05 12:44 UTC by TawR1024

Prepare for 5.5.0 release

2024-11-05 12:52 UTC, pavelpereyma requested changes

2024-11-05 12:52 UTC, pavelpereyma commented on CHANGELOG.md
> +* Added `enable_audit_logs` argument to `selectel_mks_cluster_v1` resouce
Опечатка `resouce` -> `resource`

2024-11-05 12:57 UTC, pavelpereyma approved these changes

2024-12-02 05:07 UTC, sel-bukharov submitted a review, later dismissed

2024-12-02 05:17 UTC, merged